image: python:3.7

stages:
  # - test
  - lint
  - pages

before_script:
  - conda env update --file gldeployenv.yaml
  - conda activate nestor-dev
  - poetry install

# Unit Tests:
#   stage: test
#   script:
#     - poetry run pytest

Python Code Lint:
  stage: lint
  script:
    - poetry run task format 

Deploy Docs:
  stage: pages
  script:
    - poetry run task deploy-docs
  artifacts:
    paths:
      - public
  only:
    - dev
